Repository neoforged/Documentation, pull requests merged in 2023-08, with the labels that each got.

#6 Add 1.20 changes
  docs/blockentities/ber.md
  docs/blocks/index.md
  docs/concepts/lifecycle.md
  docs/concepts/registries.md
  docs/datastorage/capabilities.md
  docs/gettingstarted/index.md
  docs/gettingstarted/modfiles.md
  docs/gui/screens.md
  docs/items/index.md
  docs/resources/server/advancements.md
  docs/resources/server/glm.md
  docs/resources/server/loottables.md
Labels: bug, documentation, enhancement

#4 Add explanation for Component and ComponentContents
  docs/concepts/internationalization.md
  docs/misc/components.md
  static/img/component_graph.png
  static/img/component_red_hello.png
  static/img/component_style_annotated.png
Labels: documentation

#7 Delete forgedev category
  docs/forgedev/index.md
  docs/forgedev/prguidelines.md
Labels: documentation

#8 Add .idea folder to gitignore
  .gitignore
Labels: enhancement
