Repository neoforged/Documentation, pull requests merged in 2024-08, with the labels that each got.

#142 Change `crafting_shapeless` -> `crafting_shaped`
  docs/resources/server/recipes/index.md
Labels: incorrect

#139 Fix menu constructor example
  docs/gui/menus.md
Labels: incorrect, typo

#138 Sort the categories in a somewhat learning curve-esque manner
  docs/advanced/_category_.json
  docs/blockentities/_category_.json
  docs/blocks/_category_.json
  docs/concepts/_category_.json
  docs/datastorage/_category_.json
  docs/datastorage/attachments.md
  docs/datastorage/capabilities.md
  docs/datastorage/codecs.md
  docs/datastorage/nbt.md
  docs/datastorage/saveddata.md
  docs/gettingstarted/_category_.json
  docs/gui/_category_.json
  docs/items/_category_.json
  docs/items/bewlr.md
  docs/items/datacomponents.md
  docs/items/interactionpipeline.md
  docs/items/mobeffects.md
  docs/items/tools.md
  docs/legacy/_category_.json
  docs/misc/_category_.json
  docs/networking/_category_.json
  docs/networking/configuration-tasks.md
  docs/networking/entities.md
  docs/networking/payload.md
  docs/networking/streamcodecs.md
  docs/resources/_category_.json
Labels: meta

#144 Update DataMapProvider example to take in holder
  docs/resources/server/datamaps/index.md
Labels: incorrect

#140 Fix particle description information
  docs/resources/client/particles.md
Labels: incorrect

#147 Document the waxables and oxidizables data maps
  docs/resources/server/datamaps/builtin.md
Labels: addition

#151 Update recipes -> recipe
  docs/resources/server/recipes/index.md
Labels: incorrect, typo

#153 Fix incorrect reference to `Attribute`
  docs/items/mobeffects.md
Labels: incorrect, typo

#155 Fix "The Crafting Mechanic" example on "Recipes"
  docs/resources/server/recipes/index.md
Labels: incorrect
