Repository neoforged/Documentation, pull requests merged in 2024-10, with the labels that each got.

#170 Fixes small typo in tools docs
  docs/items/tools.md
Labels: typo

#160 Rewrite the Block Entities section
  docs/blockentities/ber.md
  docs/blockentities/container.md
  docs/blockentities/index.md
  docs/items/bewlr.md
  docs/resources/client/models/bakedmodel.md
  docs/resources/client/models/index.md
  docs/resources/client/models/modelloaders.md
Labels: addition

#176 Resolve blocks passed to block entity
  docs/blockentities/index.md
Labels: incorrect

#107 Expand the configuration code example to give some more context
  docs/misc/config.md
Labels: addition

#165 Add Enchantments page
  docs/resources/server/enchantments/builtin.md
  docs/resources/server/enchantments/index.md
Labels: addition
