Repository neoforged/Documentation, pull requests merged in 2024-09, with the labels that each got.

#164 Update data components registrar method
  docs/datastorage/attachments.md
  docs/datastorage/nbt.md
  docs/items/datacomponents.mdx
  docs/items/index.md
  docs/items/tools.md
  docs/resources/server/datamaps/builtin.md
  docs/resources/server/loottables/lootfunctions.md
Labels: update

#161 Biome Modifier documentation
  docs/advanced/_category_.json
  docs/legacy/_category_.json
  docs/misc/_category_.json
  docs/networking/_category_.json
  docs/worldgen/_category_.json
  docs/worldgen/biomemodifier.md
Labels: addition

#167 Fix anchors in Biome Modifier docs
  docs/worldgen/biomemodifier.md
Labels: incorrect
