Repository neoforged/Documentation, pull requests merged in 2024-07, with the labels that each got.

#126 Depluralize Registry and Tag Folders
  docs/concepts/registries.md
  docs/misc/gametest.mdx
  docs/misc/resourcelocation.md
  docs/resources/index.md
  docs/resources/server/loottables.md
  docs/resources/server/recipes/index.md
Labels: incorrect

#133 Remove RegistryObject references
  docs/blockentities/index.md
  docs/gui/menus.md
  versioned_docs/version-1.20.4/blockentities/index.md
  versioned_docs/version-1.20.4/datagen/loottables.md
  versioned_docs/version-1.20.4/gui/menus.md
  versioned_docs/version-1.20.4/resources/server/glm.md
  versioned_docs/version-1.20.4/resources/server/recipes/custom.md
  versioned_docs/version-1.20.6/blockentities/index.md
  versioned_docs/version-1.20.6/gui/menus.md
  versioned_docs/version-1.20.6/resources/server/glm.md
  versioned_docs/version-1.20.6/resources/server/recipes/custom.md
Labels: update

#111 Rework server resources
  docs/concepts/registries.md
  docs/datagen/_category_.json
  docs/datagen/advancements.md
  docs/datagen/glm.md
  docs/datagen/loottables.md
  docs/datagen/recipes.md
  docs/datagen/tags.md
  docs/datamaps/_category_.json
  docs/datamaps/index.md
  docs/datamaps/neo_maps.md
  docs/datamaps/structure.md
  docs/datastorage/codecs.md
  docs/datastorage/nbt.md
  docs/items/index.md
  docs/items/mobeffects.md
  docs/resources/index.md
  docs/resources/server/_category_.json
  docs/resources/server/advancements.md
  docs/resources/server/conditional.md
  docs/resources/server/conditions.md
  docs/resources/server/damagetypes.md
  docs/resources/server/datamaps/builtin.md
  docs/resources/server/datamaps/index.md
  docs/resources/server/glm.md
  docs/resources/server/index.md
  docs/resources/server/loottables.md
  docs/resources/server/loottables/custom.md
  docs/resources/server/loottables/glm.md
  docs/resources/server/loottables/index.md
  docs/resources/server/loottables/lootconditions.md
  docs/resources/server/loottables/lootfunctions.md
  docs/resources/server/recipes/builtin.md
  docs/resources/server/recipes/custom.md
  docs/resources/server/recipes/incode.md
  docs/resources/server/recipes/index.md
  docs/resources/server/recipes/ingredients.md
  docs/resources/server/tags.md
Labels: addition, large

#137 Add configuration screen documentation
  docs/misc/config.md
Labels: addition
