Repository neoforged/Documentation, pull requests merged in 2024-06, with the labels that each got.

#103 Update to new enum extension system
  docs/advanced/extensibleenums.md
  docs/gettingstarted/modfiles.md
Labels: update

#116 Fix ClientTickEvent phases no longer existing
  docs/misc/keymappings.md
Labels: incorrect, update

#114 Register Armor Materials in Example
  docs/items/tools.md
Labels: incorrect

#117 Switch data component registration to specialized DeferredRegister
  docs/items/datacomponents.md
Labels: addition

#119 Readd Information about PacketDistributor
  docs/networking/payload.md
  versioned_docs/version-1.20.6/networking/index.md
  versioned_docs/version-1.20.6/networking/payload.md
Labels: incorrect, addition

#122 Update ToolAction -> ItemAbility
  docs/items/tools.md
  docs/resources/server/loottables.md
Labels: incorrect, update

#124 Fix particle example to avoid NPE
  docs/resources/client/particles.md
Labels: incorrect
