Repository neoforged/Documentation, pull requests merged in 2025-09, with the labels that each got.

#278 Clarify Data Synchronization in Menus
  docs/gui/menus.md
Labels: update

#280 Fix block implementation example
  docs/gui/menus.md
  versioned_docs/version-1.20.6/gui/menus.md
  versioned_docs/version-1.21.1/gui/menus.md
  versioned_docs/version-1.21.3/gui/menus.md
  versioned_docs/version-1.21.4/gui/menus.md
  versioned_docs/version-1.21.5/gui/menus.md
Labels: incorrect

#282 Use npm ci in CI/CD
  .github/workflows/build-pr.yml
  .github/workflows/version-update.yml
Labels: meta

#281 Add Neo Releases as Primer Embeds
  scripts/initialize.js
Labels: meta

#283 Correct the keys stated to be used in the oxidized data map
  versioned_docs/version-1.21.1/resources/server/datamaps/builtin.md
  versioned_docs/version-1.21.3/resources/server/datamaps/builtin.md
  versioned_docs/version-1.21.4/resources/server/datamaps/builtin.md
  versioned_docs/version-1.21.5/resources/server/datamaps/builtin.md
Labels: incorrect
